### ISSUE TITLE
reload! method in zeus console 

### ISSUE THREAD

**Issue by kisakov** [burke/zeus#466]
In new zeus (v 0.15.1) in zeus console(pry) method reload! doesn't work.

``` ruby
reload!
NoMethodError: undefined method `reload!' for main:Object
from (pry):1:in `<main>'
```

But in simple rails c it's method work's.
Thank you for you support!

**Comment by icortex** [comment]
The code by @halostatue worked for me. Thanks!

**Comment by lazywei** [comment]
Why this is still closed? As @halostatue said, this workaround is not making sense to me. I feel zeus should handle this, shouldn't it?

**Comment by eyaleizenberg** [comment]
Thanks @halostatue !

**Comment by hraynaud** [comment]
@halostatue 's code works for me as well. Would love to have this resolved with having to patch the .pryrc

**Comment by ccmcbeck** [comment]
So glad to have found this workaround.  So I'll perturb this thread.

**Comment by ryankc33** [comment]
@halostatue's workaround worked for me. 

reload! was working fine with vanilla rails c and pry, but ran into the NoMethodError with zeus 0.15.5

**Comment by joonty** [comment]
Think this needs a bump, as it's still an issue and still closed.
